//
// Auto-generated by edu.vanderbilt.riaps.generator.ComponenetGenerator.xtend
//
#ifndef RIAPS_FW_MEMLIMIT_H
#define RIAPS_FW_MEMLIMIT_H

#include "MemLimitBase.h"

namespace limits {
   namespace components {
      
      class MemLimit : public MemLimitBase {
         
         public:
         
         MemLimit(_component_conf &config, riaps::Actor &actor);
         
         virtual void OnTicker(riaps::ports::PortBase *port);
         
         void OnGroupMessage(const riaps::groups::GroupId& groupId, capnp::FlatArrayMessageReader& capnpreader, riaps::ports::PortBase* port);
         
         virtual ~MemLimit();
         
      };
   }
}

extern "C" riaps::ComponentBase* create_component(_component_conf&, riaps::Actor& actor);
extern "C" void destroy_component(riaps::ComponentBase*);


#endif //RIAPS_FW_MEMLIMIT_H
