set(CMAKE_SYSTEM_NAME Linux)
set(RIAPS_PREFIX /opt/riaps/amd64/)
set(ARCH amd64)
set(CMAKE_C_COMPILER gcc)
set(CMAKE_CXX_COMPILER g++)
set(CMAKE_FIND_ROOT_PATH /usr/)
set (CMAKE_CXX_FLAGS "-std=c++11")
set (CMAKE_C_FLAGS "-std=c99")
include_directories(${RIAPS_PREFIX}/include)			
