sudo: required
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
env:
  global:
    secure: pL9FNcvvryS/pcuaJPofKRc4EgkEswlIfqnKoR/cxqBeSaeDMzBdXqtXUmBIxzYqo+nIiTaePr2ekS86sPtjrgO91WcK8GeLrPlaeehAkVKFhx8IKVJ8V6F+SnNcw11iZLG6B5ooFVuThAWHs3BUhy7ukZHh5RB6zCGfpxvFu7tw0xnanGylg8eEfjnJyybcNKcqr6IGS3jhc8hOulQYPppbjsTNH8iFThnpWSX4soW1sVsg4PcEF9N8/NpOpVokjcin6JxdomkfrsuN3d09Uq8vEiD+GOk4etKb2o8CW1381dste62LL1WFKlbtVb+PgEN65BKQu+42sv0nsgrjbEu6XrKnE1IEWztAGD/DC/RyxbPUZnRPPyb0qub0jNzUhtAFvCtJ00dZt/1PsxbEBCWNgxKdPrykaGy3S5pvE1zyDp/4G9kfqYl7XUOMkfMX9KoYUF903DxJ6eUlInrox6J/d02VknYW6DavWULbbFIfb1C0DUqk1mj4cSggjWA01qxSAtj7ClnudpQLhlMIV5/HpO7jOQtryH/U4KH3hw7da0AHl1xRUKsN/lkqBtQOHS74lRu6I6RFhignglNU7tYdw4h00224HVVBVnhel2ih4ajexy5b18zE7o9Rc+smzz1LLgv0gBgJbEK+8KQDVnGDbIDvHoTYkUzueIwQQsM=
before_script:
- source version.sh
- wget https://github.com/gruntwork-io/fetch/releases/download/v0.1.1/fetch_linux_amd64
- source version.sh
- chmod +x fetch_linux_amd64
- ./fetch_linux_amd64 --repo="https://github.com/RIAPS/riaps-externals/" --tag=$externalsversion
  --release-asset="riaps-externals-amd64.deb" .
- sudo dpkg -i riaps-externals-amd64.deb
- sudo add-apt-repository 'deb http://fr.archive.ubuntu.com/ubuntu/ wily main'
- sudo apt-get update
- sudo apt-get install g++-5-arm-linux-gnueabihf g++-5 fakeroot
- sudo rm -f /usr/bin/arm-linux-gnueabihf-gcc
- sudo rm -f /usr/bin/arm-linux-gnueabihf-g++
- sudo ln -s /usr/bin/arm-linux-gnueabihf-gcc-5 /usr/bin/arm-linux-gnueabihf-gcc
- sudo ln -s /usr/bin/arm-linux-gnueabihf-g++-5 /usr/bin/arm-linux-gnueabihf-g++
- sudo rm -f /usr/bin/gcc
- sudo rm -f /usr/bin/g++
- sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
- sudo ln -s /usr/bin/g++-5 /usr/bin/g++
script:
- g++-5 -v
- chmod +x build.sh package.sh
- "./build.sh &&  ./package.sh"
deploy:
  provider: releases
  overwrite: true
  api_key:
    secure: eKL5j2VunlQ74uiHzFW191CTsFFOPbcQDEdaQIVYtmakRht/0rBB1rQxpYzPhYQDRZ17vqN35N/giy6WEL8phyUbiM7k7fByQTe7isrCRMuAWQj5eH3rzhq9bvyqMQWTBFAZUSq2c7BGgfHr3c9lxHCKCMd4hmbAc3XTpiLbOmkfOYUcBrCXM2uY/MHu3Zt7d/JOPeAyBeLn1dShr3YmmQ9wSkw/3KxKEsFP8wTj8crK8NX+IkpE6N0d9gS6lIcxLrZ7qHJbNiDpeUDnaZxquM9fPEI9PIaZw9J/uZo9wkycB/2dB1a/NTVS9AwwaKsfg22YDSlwKBKjFHM0K5kFpN7Lhu17KQqfglY0Bguiyw4MdMcj7MeBaKkx69961ig2lhBT0t8jnY8KpjsHAXZaMKWN/Jyqv0+EwpLPNjmFVFqT7qtIXfgrmpJPQBaI2swHbVkRA0gypl/s9zSOIqtvz93guSmZ5anWEh6Ik9jX/ESNWHxaSnHiUYYLSNJe4HqffHmG9uXDW9ITk178DbsjvI2MudzSfLNUD72DJYgMw3M78vASV0XDenqBuWo28yJ7n2L2TbpUpeTvfxlslXIVFrwtPPe9Chf5gqoe6BsrjyfGQrXBTInwb/++jWfrG/vztuW4m2E8qUYipyBe4J5fsnJpopjgC7/QZletikXngMI=
  file:
  - package/riaps-core-amd64.deb
  - package/riaps-core-armhf.deb
  skip_cleanup: true
  on:
    tags: true
