sudo: required
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - g++-arm-linux-gnueabihf
    - capnproto
env:
  global:
    -  secure: dItmuutoyf9tBY7nyiK2qTb0od72AataLLuFoBqNTYmcFDg/xNuwHvwAAcu1jG4a9SSQS3jxcTRGn3J5hmRVRprpoJOeao8LRyXd3s1xBHKRjoutqKXAJSxJyJgZZED+qrYBok0s1spoQf0uGnwruJgXuZZhPmEAcfPowrgz0SPHGmNT4EbcZ1rJoZKi6wxmYNvgeaI52++zA7XRH6Vfyw3cGDyAsvD/02hLDhg0PCu0Y3eHLYCGTpBbb6MoieCNiDj43UPdxi7x95wr4hhseu4ObLFDLSyZbFjYfTQygkas4Xgg7X7myGwF3kG3YT1ZWNSgP1ZSk2MBXdRVfvRy13EMscWuCAMFSBrwS+6iRsPys9NAjj2eX9PzlBA4VVse5VBx7FblJ3eVE8LljUBZjWj4oYh078GIZ6I7DljnJk6queY0PbKOodEfZzoXa1QC+NswawpU6U85NwYjnet3FUVALJ2GAUbwkR8Vjfk+jzw6/7IyS2tyBhfQdhCuakJJw/bgu7ny05yuLBZy0m1rIrQzCQHxxzNvtIF9vXoHvqdjF5UcSwwwpzojYdUY/rkVhtGkcFl4Q3+MIbyOfK4N12CtoOlwT82T3F/GFdGeWY1JGTwJvLSqBN0HWBmJqFajhL3ceGczcmQDiB+ZO5DUrl4D7l8tXWMaJyM2Y7aOsFw=
  matrix:
    - arch=amd64
    - arch=armhf
  
before_script:
  - wget https://github.com/gruntwork-io/fetch/releases/download/v0.1.1/fetch_linux_amd64
  - chmod +x fetch_linux_amd64
  - ./fetch_linux_amd64 --repo="https://github.com/RIAPS/externals/" --tag="0.2" --release-asset="riaps-externals-armhf.deb" .
  - ./fetch_linux_amd64 --repo="https://github.com/RIAPS/externals/" --tag="0.2" --release-asset="riaps-externals-amd64.deb" .
  - sudo dpkg -i riaps-externals-armhf.deb
  - sudo dpkg -i riaps-externals-amd64.deb

script:
- mkdir build-$arch
- cd build-$arch
- cmake -Darch=$arch  ..
- PATH=/opt/riaps/amd64/bin:$PATH make

