sudo: required
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
env:
  global:
    secure: pL9FNcvvryS/pcuaJPofKRc4EgkEswlIfqnKoR/cxqBeSaeDMzBdXqtXUmBIxzYqo+nIiTaePr2ekS86sPtjrgO91WcK8GeLrPlaeehAkVKFhx8IKVJ8V6F+SnNcw11iZLG6B5ooFVuThAWHs3BUhy7ukZHh5RB6zCGfpxvFu7tw0xnanGylg8eEfjnJyybcNKcqr6IGS3jhc8hOulQYPppbjsTNH8iFThnpWSX4soW1sVsg4PcEF9N8/NpOpVokjcin6JxdomkfrsuN3d09Uq8vEiD+GOk4etKb2o8CW1381dste62LL1WFKlbtVb+PgEN65BKQu+42sv0nsgrjbEu6XrKnE1IEWztAGD/DC/RyxbPUZnRPPyb0qub0jNzUhtAFvCtJ00dZt/1PsxbEBCWNgxKdPrykaGy3S5pvE1zyDp/4G9kfqYl7XUOMkfMX9KoYUF903DxJ6eUlInrox6J/d02VknYW6DavWULbbFIfb1C0DUqk1mj4cSggjWA01qxSAtj7ClnudpQLhlMIV5/HpO7jOQtryH/U4KH3hw7da0AHl1xRUKsN/lkqBtQOHS74lRu6I6RFhignglNU7tYdw4h00224HVVBVnhel2ih4ajexy5b18zE7o9Rc+smzz1LLgv0gBgJbEK+8KQDVnGDbIDvHoTYkUzueIwQQsM=
before_script:
- source version.sh
- wget https://github.com/gruntwork-io/fetch/releases/download/v0.1.1/fetch_linux_amd64
- source version.sh
- chmod +x fetch_linux_amd64
- ./fetch_linux_amd64 --repo="https://github.com/RIAPS/riaps-externals/" --tag=$externalsversion
  --release-asset="riaps-externals-amd64.deb" .
- sudo dpkg -i riaps-externals-amd64.deb
#- sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu/ wily main'
- sudo apt-get update
- sudo apt-get install g++-5-arm-linux-gnueabihf g++-5 fakeroot
- sudo rm -f /usr/bin/arm-linux-gnueabihf-gcc
- sudo rm -f /usr/bin/arm-linux-gnueabihf-g++
- sudo ln -s /usr/bin/arm-linux-gnueabihf-gcc-5 /usr/bin/arm-linux-gnueabihf-gcc
- sudo ln -s /usr/bin/arm-linux-gnueabihf-g++-5 /usr/bin/arm-linux-gnueabihf-g++
- sudo rm -f /usr/bin/gcc
- sudo rm -f /usr/bin/g++
- sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
- sudo ln -s /usr/bin/g++-5 /usr/bin/g++
script:
- g++-5 -v
- chmod +x build.sh package.sh
- "./build.sh &&  ./package.sh"
deploy:
  provider: releases
  overwrite: true
  api_key:
   secure: KnvBXovgqVHHeb4+A4eOfeYnRPKGyUTJfjcdNvtQfl7snT4CqhTNIBsvhJ0uOgEr0ohQWoq2uw+TRPVgt3smhlpqAszWKpSGdkXKvrz+CXzLmzarOGvQ17Jda888kuSgVzzuNsFkXYFcsFu15cbO+Csm5yk+ocE22gheDsnQkgTgJlTylSU1+/ki1/bo7fDM++O43eBWvbIO6YausELZVfo3xvn++y6FBwLeFGABaDBcASfmdagE1NrrLCMjkWkOYJjSGv75MwCCp4aGBM1D30cjI4RlIr1E7bUme120F9lk8A/krjuhm5BWZEHSp/9e8qgmoD9+4whCfn1KAdyXffFf6E060XwbOFSvwhPEiqaY+8HW6/J9OSCABUdPrC54Z/ngCZv8QNoSBP3IdAHdM6UjmBLh0nHtI7AOaEF2WnxB6GLqUTO1gP1Vr6NGj55x9NNJYkfqDlZ5du66ZDbmkn50Cszkct+AJvKSEWJA214RwlXX880f3s5CuRx/S+NA1AqVN5a+YJJ/o+LpmTC7D5mXai8iuKEV2G46i/O8x9YswAXQ/rgF3Tby3r2drqOPTu5Tczr4nlJf5b/iJ/W70pfrUxBklBSsQJoXL19hDMoErKPZkIZCgytJx+N7QQRzr2FvuQiqInBC6l1mYXeAhQcMCeWBWdLQp2WOHfyrmqc=
  file:
  - package/riaps-core-amd64.deb
  - package/riaps-core-armhf.deb
  skip_cleanup: true
  on:
    tags: true
