
#ifndef RIAPS_CORE_GROUPTYPES_H
#define RIAPS_CORE_GROUPTYPES_H

// GroupType Ids
#define GROUPTYPE_BACKUPGROUP               "BackupGroup"
#define GROUPPORT_BACKUPGROUP_QUERY_OUT     "QueryOut"
#define GROUPPORT_BACKUPGROUP_QUERY_IN      "QueryIn"
#define GROUPPORT_BACKUPGROUP_RESPONSE_OUT  "ResponseOut"
#define GROUPPORT_BACKUPGROUP_RESPONSE_IN   "ResponseIn"

#endif //RIAPS_CORE_GROUPTYPES_H
