//
// Created by istvan on 2/5/17.
//

#ifndef RIAPS_CORE_R_DISCOVERYD_COMMANDS_H_H
#define RIAPS_CORE_R_DISCOVERYD_COMMANDS_H_H

#define CMD_JOIN "JOIN"

#endif //RIAPS_CORE_R_DISCOVERYD_COMMANDS_H_H
