//
// Auto-generated by edu.vanderbilt.riaps.generator.ComponenetGenerator.xtend
//
#ifndef RIAPS_FW_TEMPMONITOR_H
#define RIAPS_FW_TEMPMONITOR_H

#include "base/TempMonitorBase.h"

namespace weathermonitor {
    namespace components {

        class TempMonitor : public TempMonitorBase {

        public:

            TempMonitor(const py::object *parent_actor,
                        const py::dict actor_spec, // Actor json config
                        const py::dict type_spec,  // component json config
                        const std::string &name,
                        const std::string &type_name,
                        const py::dict args,
                        const std::string &application_name,
                        const std::string &actor_name);

            virtual void OnTempupdate(const messages::TempData::Reader &message, riaps::ports::PortBase *port);
            virtual ~TempMonitor() = default;
        };
    }
}

std::unique_ptr<weathermonitor::components::TempMonitor>
create_component_py(const py::object *parent_actor,
                    const py::dict actor_spec,
                    const py::dict type_spec,
                    const std::string &name,
                    const std::string &type_name,
                    const py::dict args,
                    const std::string &application_name,
                    const std::string &actor_name);


#endif //RIAPS_FW_TEMPMONITOR_H		
