//
// Auto-generated by edu.vanderbilt.riaps.generator.ComponenetGenerator.xtend
//

#ifndef RIAPS_CORE_TEMPMONITOR_H
#define RIAPS_CORE_TEMPMONITOR_H

#include "componentmodel/r_componentbase.h"
#include "messages/TempData.capnp.h"

#include <pybind11/stl.h>
#include <pybind11/pybind11.h>

// Name of the ports from the model file
constexpr auto PORT_SUB_TEMPUPDATE = "tempupdate";



namespace py = pybind11;

namespace weathermonitor {
    namespace components {
    	
    	class TempMonitorBase : public riaps::ComponentBase {
    		
    	public:
    		TempMonitorBase(const py::object *parent_actor,
							const py::dict    actor_spec, // Actor json config
							const py::dict    type_spec,  // component json config
							const std::string &name,
							const std::string &type_name,
							const py::dict    args,
							const std::string &application_name,
							const std::string &actor_name);
    		
    		virtual void OnTempupdate (const messages::TempData::Reader &message, riaps::ports::PortBase *port)=0;
    		
    	    virtual ~TempMonitorBase() = default;
    	protected:
			virtual void DispatchMessage(capnp::FlatArrayMessageReader* capnpreader,
										 riaps::ports::PortBase*   port,
										 std::shared_ptr<riaps::MessageParams> params) final;

			virtual void DispatchInsideMessage(zmsg_t* zmsg,
											   riaps::ports::PortBase* port) final;
        };
    }
}
#endif //RIAPS_CORE_TEMPMONITOR_H	
