// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: distcoord.capnp

#ifndef CAPNP_INCLUDED_a5b4ccd232a91945_
#define CAPNP_INCLUDED_a5b4ccd232a91945_

#include <capnp/generated-header-support.h>

#if CAPNP_VERSION != 5003
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(fce2365756d7b39d);
enum class HeartBeatType_fce2365756d7b39d: uint16_t {
  PING,
  PONG,
};
CAPNP_DECLARE_ENUM(HeartBeatType, fce2365756d7b39d);
CAPNP_DECLARE_SCHEMA(c7426d39bcaf282b);
CAPNP_DECLARE_SCHEMA(d8629c14bc7a91fa);
CAPNP_DECLARE_SCHEMA(8d54747aa35f644c);
CAPNP_DECLARE_SCHEMA(f94e1231cc4b13d6);
CAPNP_DECLARE_SCHEMA(f33d21662bc326c4);
CAPNP_DECLARE_SCHEMA(8a25ecc657bf2ed3);

}  // namespace schemas
}  // namespace capnp

namespace riaps {
namespace distrcoord {

typedef ::capnp::schemas::HeartBeatType_fce2365756d7b39d HeartBeatType;

struct GroupHeartBeat {
  GroupHeartBeat() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(c7426d39bcaf282b, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand = &schema->defaultBrand;
    #endif  // !CAPNP_LITE
  };
};

struct LeaderHeartBeat {
  LeaderHeartBeat() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(d8629c14bc7a91fa, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand = &schema->defaultBrand;
    #endif  // !CAPNP_LITE
  };
};

struct RequestForVoteReq {
  RequestForVoteReq() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(8d54747aa35f644c, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand = &schema->defaultBrand;
    #endif  // !CAPNP_LITE
  };
};

struct RequestForVoteRep {
  RequestForVoteRep() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(f94e1231cc4b13d6, 0, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand = &schema->defaultBrand;
    #endif  // !CAPNP_LITE
  };
};

struct LeaderElection {
  LeaderElection() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(f33d21662bc326c4, 0, 3)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand = &schema->defaultBrand;
    #endif  // !CAPNP_LITE
  };
};

struct GroupInternals {
  GroupInternals() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  enum Which: uint16_t {
    GROUP_HEART_BEAT,
    LEADER_ELECTION,
  };

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(8a25ecc657bf2ed3, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand = &schema->defaultBrand;
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class GroupHeartBeat::Reader {
public:
  typedef GroupHeartBeat Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand);
  }
#endif  // !CAPNP_LITE

  inline  ::riaps::distrcoord::HeartBeatType getHeartBeatType() const;

  inline bool hasSourceComponentId() const;
  inline  ::capnp::Text::Reader getSourceComponentId() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class GroupHeartBeat::Builder {
public:
  typedef GroupHeartBeat Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::riaps::distrcoord::HeartBeatType getHeartBeatType();
  inline void setHeartBeatType( ::riaps::distrcoord::HeartBeatType value);

  inline bool hasSourceComponentId();
  inline  ::capnp::Text::Builder getSourceComponentId();
  inline void setSourceComponentId( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initSourceComponentId(unsigned int size);
  inline void adoptSourceComponentId(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownSourceComponentId();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class GroupHeartBeat::Pipeline {
public:
  typedef GroupHeartBeat Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class LeaderHeartBeat::Reader {
public:
  typedef LeaderHeartBeat Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand);
  }
#endif  // !CAPNP_LITE

  inline bool hasSourceComponentId() const;
  inline  ::capnp::Text::Reader getSourceComponentId() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class LeaderHeartBeat::Builder {
public:
  typedef LeaderHeartBeat Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasSourceComponentId();
  inline  ::capnp::Text::Builder getSourceComponentId();
  inline void setSourceComponentId( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initSourceComponentId(unsigned int size);
  inline void adoptSourceComponentId(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownSourceComponentId();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class LeaderHeartBeat::Pipeline {
public:
  typedef LeaderHeartBeat Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class RequestForVoteReq::Reader {
public:
  typedef RequestForVoteReq Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand);
  }
#endif  // !CAPNP_LITE

  inline bool hasSourceComponentId() const;
  inline  ::capnp::Text::Reader getSourceComponentId() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class RequestForVoteReq::Builder {
public:
  typedef RequestForVoteReq Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasSourceComponentId();
  inline  ::capnp::Text::Builder getSourceComponentId();
  inline void setSourceComponentId( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initSourceComponentId(unsigned int size);
  inline void adoptSourceComponentId(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownSourceComponentId();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class RequestForVoteReq::Pipeline {
public:
  typedef RequestForVoteReq Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class RequestForVoteRep::Reader {
public:
  typedef RequestForVoteRep Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand);
  }
#endif  // !CAPNP_LITE

  inline bool hasSourceComponentId() const;
  inline  ::capnp::Text::Reader getSourceComponentId() const;

  inline bool hasVoteForId() const;
  inline  ::capnp::Text::Reader getVoteForId() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class RequestForVoteRep::Builder {
public:
  typedef RequestForVoteRep Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasSourceComponentId();
  inline  ::capnp::Text::Builder getSourceComponentId();
  inline void setSourceComponentId( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initSourceComponentId(unsigned int size);
  inline void adoptSourceComponentId(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownSourceComponentId();

  inline bool hasVoteForId();
  inline  ::capnp::Text::Builder getVoteForId();
  inline void setVoteForId( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initVoteForId(unsigned int size);
  inline void adoptVoteForId(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownVoteForId();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class RequestForVoteRep::Pipeline {
public:
  typedef RequestForVoteRep Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class LeaderElection::Reader {
public:
  typedef LeaderElection Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand);
  }
#endif  // !CAPNP_LITE

  inline bool hasLeaderHeartBeat() const;
  inline  ::riaps::distrcoord::LeaderHeartBeat::Reader getLeaderHeartBeat() const;

  inline bool hasRequestForVoteReq() const;
  inline  ::riaps::distrcoord::RequestForVoteReq::Reader getRequestForVoteReq() const;

  inline bool hasRequestForVoteRep() const;
  inline  ::riaps::distrcoord::RequestForVoteRep::Reader getRequestForVoteRep() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class LeaderElection::Builder {
public:
  typedef LeaderElection Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasLeaderHeartBeat();
  inline  ::riaps::distrcoord::LeaderHeartBeat::Builder getLeaderHeartBeat();
  inline void setLeaderHeartBeat( ::riaps::distrcoord::LeaderHeartBeat::Reader value);
  inline  ::riaps::distrcoord::LeaderHeartBeat::Builder initLeaderHeartBeat();
  inline void adoptLeaderHeartBeat(::capnp::Orphan< ::riaps::distrcoord::LeaderHeartBeat>&& value);
  inline ::capnp::Orphan< ::riaps::distrcoord::LeaderHeartBeat> disownLeaderHeartBeat();

  inline bool hasRequestForVoteReq();
  inline  ::riaps::distrcoord::RequestForVoteReq::Builder getRequestForVoteReq();
  inline void setRequestForVoteReq( ::riaps::distrcoord::RequestForVoteReq::Reader value);
  inline  ::riaps::distrcoord::RequestForVoteReq::Builder initRequestForVoteReq();
  inline void adoptRequestForVoteReq(::capnp::Orphan< ::riaps::distrcoord::RequestForVoteReq>&& value);
  inline ::capnp::Orphan< ::riaps::distrcoord::RequestForVoteReq> disownRequestForVoteReq();

  inline bool hasRequestForVoteRep();
  inline  ::riaps::distrcoord::RequestForVoteRep::Builder getRequestForVoteRep();
  inline void setRequestForVoteRep( ::riaps::distrcoord::RequestForVoteRep::Reader value);
  inline  ::riaps::distrcoord::RequestForVoteRep::Builder initRequestForVoteRep();
  inline void adoptRequestForVoteRep(::capnp::Orphan< ::riaps::distrcoord::RequestForVoteRep>&& value);
  inline ::capnp::Orphan< ::riaps::distrcoord::RequestForVoteRep> disownRequestForVoteRep();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class LeaderElection::Pipeline {
public:
  typedef LeaderElection Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::riaps::distrcoord::LeaderHeartBeat::Pipeline getLeaderHeartBeat();
  inline  ::riaps::distrcoord::RequestForVoteReq::Pipeline getRequestForVoteReq();
  inline  ::riaps::distrcoord::RequestForVoteRep::Pipeline getRequestForVoteRep();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class GroupInternals::Reader {
public:
  typedef GroupInternals Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand);
  }
#endif  // !CAPNP_LITE

  inline Which which() const;
  inline bool isGroupHeartBeat() const;
  inline bool hasGroupHeartBeat() const;
  inline  ::riaps::distrcoord::GroupHeartBeat::Reader getGroupHeartBeat() const;

  inline bool isLeaderElection() const;
  inline bool hasLeaderElection() const;
  inline  ::riaps::distrcoord::LeaderElection::Reader getLeaderElection() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class GroupInternals::Builder {
public:
  typedef GroupInternals Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline Which which();
  inline bool isGroupHeartBeat();
  inline bool hasGroupHeartBeat();
  inline  ::riaps::distrcoord::GroupHeartBeat::Builder getGroupHeartBeat();
  inline void setGroupHeartBeat( ::riaps::distrcoord::GroupHeartBeat::Reader value);
  inline  ::riaps::distrcoord::GroupHeartBeat::Builder initGroupHeartBeat();
  inline void adoptGroupHeartBeat(::capnp::Orphan< ::riaps::distrcoord::GroupHeartBeat>&& value);
  inline ::capnp::Orphan< ::riaps::distrcoord::GroupHeartBeat> disownGroupHeartBeat();

  inline bool isLeaderElection();
  inline bool hasLeaderElection();
  inline  ::riaps::distrcoord::LeaderElection::Builder getLeaderElection();
  inline void setLeaderElection( ::riaps::distrcoord::LeaderElection::Reader value);
  inline  ::riaps::distrcoord::LeaderElection::Builder initLeaderElection();
  inline void adoptLeaderElection(::capnp::Orphan< ::riaps::distrcoord::LeaderElection>&& value);
  inline ::capnp::Orphan< ::riaps::distrcoord::LeaderElection> disownLeaderElection();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class GroupInternals::Pipeline {
public:
  typedef GroupInternals Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline  ::riaps::distrcoord::HeartBeatType GroupHeartBeat::Reader::getHeartBeatType() const {
  return _reader.getDataField< ::riaps::distrcoord::HeartBeatType>(
      0 * ::capnp::ELEMENTS);
}

inline  ::riaps::distrcoord::HeartBeatType GroupHeartBeat::Builder::getHeartBeatType() {
  return _builder.getDataField< ::riaps::distrcoord::HeartBeatType>(
      0 * ::capnp::ELEMENTS);
}
inline void GroupHeartBeat::Builder::setHeartBeatType( ::riaps::distrcoord::HeartBeatType value) {
  _builder.setDataField< ::riaps::distrcoord::HeartBeatType>(
      0 * ::capnp::ELEMENTS, value);
}

inline bool GroupHeartBeat::Reader::hasSourceComponentId() const {
  return !_reader.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline bool GroupHeartBeat::Builder::hasSourceComponentId() {
  return !_builder.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader GroupHeartBeat::Reader::getSourceComponentId() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(
      _reader.getPointerField(0 * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder GroupHeartBeat::Builder::getSourceComponentId() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}
inline void GroupHeartBeat::Builder::setSourceComponentId( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(
      _builder.getPointerField(0 * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder GroupHeartBeat::Builder::initSourceComponentId(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(
      _builder.getPointerField(0 * ::capnp::POINTERS), size);
}
inline void GroupHeartBeat::Builder::adoptSourceComponentId(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(
      _builder.getPointerField(0 * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> GroupHeartBeat::Builder::disownSourceComponentId() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}

inline bool LeaderHeartBeat::Reader::hasSourceComponentId() const {
  return !_reader.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline bool LeaderHeartBeat::Builder::hasSourceComponentId() {
  return !_builder.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader LeaderHeartBeat::Reader::getSourceComponentId() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(
      _reader.getPointerField(0 * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder LeaderHeartBeat::Builder::getSourceComponentId() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}
inline void LeaderHeartBeat::Builder::setSourceComponentId( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(
      _builder.getPointerField(0 * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder LeaderHeartBeat::Builder::initSourceComponentId(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(
      _builder.getPointerField(0 * ::capnp::POINTERS), size);
}
inline void LeaderHeartBeat::Builder::adoptSourceComponentId(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(
      _builder.getPointerField(0 * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> LeaderHeartBeat::Builder::disownSourceComponentId() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}

inline bool RequestForVoteReq::Reader::hasSourceComponentId() const {
  return !_reader.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline bool RequestForVoteReq::Builder::hasSourceComponentId() {
  return !_builder.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader RequestForVoteReq::Reader::getSourceComponentId() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(
      _reader.getPointerField(0 * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder RequestForVoteReq::Builder::getSourceComponentId() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}
inline void RequestForVoteReq::Builder::setSourceComponentId( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(
      _builder.getPointerField(0 * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder RequestForVoteReq::Builder::initSourceComponentId(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(
      _builder.getPointerField(0 * ::capnp::POINTERS), size);
}
inline void RequestForVoteReq::Builder::adoptSourceComponentId(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(
      _builder.getPointerField(0 * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> RequestForVoteReq::Builder::disownSourceComponentId() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}

inline bool RequestForVoteRep::Reader::hasSourceComponentId() const {
  return !_reader.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline bool RequestForVoteRep::Builder::hasSourceComponentId() {
  return !_builder.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader RequestForVoteRep::Reader::getSourceComponentId() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(
      _reader.getPointerField(0 * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder RequestForVoteRep::Builder::getSourceComponentId() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}
inline void RequestForVoteRep::Builder::setSourceComponentId( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(
      _builder.getPointerField(0 * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder RequestForVoteRep::Builder::initSourceComponentId(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(
      _builder.getPointerField(0 * ::capnp::POINTERS), size);
}
inline void RequestForVoteRep::Builder::adoptSourceComponentId(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(
      _builder.getPointerField(0 * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> RequestForVoteRep::Builder::disownSourceComponentId() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}

inline bool RequestForVoteRep::Reader::hasVoteForId() const {
  return !_reader.getPointerField(1 * ::capnp::POINTERS).isNull();
}
inline bool RequestForVoteRep::Builder::hasVoteForId() {
  return !_builder.getPointerField(1 * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader RequestForVoteRep::Reader::getVoteForId() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(
      _reader.getPointerField(1 * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder RequestForVoteRep::Builder::getVoteForId() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(
      _builder.getPointerField(1 * ::capnp::POINTERS));
}
inline void RequestForVoteRep::Builder::setVoteForId( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(
      _builder.getPointerField(1 * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder RequestForVoteRep::Builder::initVoteForId(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(
      _builder.getPointerField(1 * ::capnp::POINTERS), size);
}
inline void RequestForVoteRep::Builder::adoptVoteForId(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(
      _builder.getPointerField(1 * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> RequestForVoteRep::Builder::disownVoteForId() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(
      _builder.getPointerField(1 * ::capnp::POINTERS));
}

inline bool LeaderElection::Reader::hasLeaderHeartBeat() const {
  return !_reader.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline bool LeaderElection::Builder::hasLeaderHeartBeat() {
  return !_builder.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline  ::riaps::distrcoord::LeaderHeartBeat::Reader LeaderElection::Reader::getLeaderHeartBeat() const {
  return ::capnp::_::PointerHelpers< ::riaps::distrcoord::LeaderHeartBeat>::get(
      _reader.getPointerField(0 * ::capnp::POINTERS));
}
inline  ::riaps::distrcoord::LeaderHeartBeat::Builder LeaderElection::Builder::getLeaderHeartBeat() {
  return ::capnp::_::PointerHelpers< ::riaps::distrcoord::LeaderHeartBeat>::get(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::riaps::distrcoord::LeaderHeartBeat::Pipeline LeaderElection::Pipeline::getLeaderHeartBeat() {
  return  ::riaps::distrcoord::LeaderHeartBeat::Pipeline(_typeless.getPointerField(0));
}
#endif  // !CAPNP_LITE
inline void LeaderElection::Builder::setLeaderHeartBeat( ::riaps::distrcoord::LeaderHeartBeat::Reader value) {
  ::capnp::_::PointerHelpers< ::riaps::distrcoord::LeaderHeartBeat>::set(
      _builder.getPointerField(0 * ::capnp::POINTERS), value);
}
inline  ::riaps::distrcoord::LeaderHeartBeat::Builder LeaderElection::Builder::initLeaderHeartBeat() {
  return ::capnp::_::PointerHelpers< ::riaps::distrcoord::LeaderHeartBeat>::init(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}
inline void LeaderElection::Builder::adoptLeaderHeartBeat(
    ::capnp::Orphan< ::riaps::distrcoord::LeaderHeartBeat>&& value) {
  ::capnp::_::PointerHelpers< ::riaps::distrcoord::LeaderHeartBeat>::adopt(
      _builder.getPointerField(0 * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::riaps::distrcoord::LeaderHeartBeat> LeaderElection::Builder::disownLeaderHeartBeat() {
  return ::capnp::_::PointerHelpers< ::riaps::distrcoord::LeaderHeartBeat>::disown(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}

inline bool LeaderElection::Reader::hasRequestForVoteReq() const {
  return !_reader.getPointerField(1 * ::capnp::POINTERS).isNull();
}
inline bool LeaderElection::Builder::hasRequestForVoteReq() {
  return !_builder.getPointerField(1 * ::capnp::POINTERS).isNull();
}
inline  ::riaps::distrcoord::RequestForVoteReq::Reader LeaderElection::Reader::getRequestForVoteReq() const {
  return ::capnp::_::PointerHelpers< ::riaps::distrcoord::RequestForVoteReq>::get(
      _reader.getPointerField(1 * ::capnp::POINTERS));
}
inline  ::riaps::distrcoord::RequestForVoteReq::Builder LeaderElection::Builder::getRequestForVoteReq() {
  return ::capnp::_::PointerHelpers< ::riaps::distrcoord::RequestForVoteReq>::get(
      _builder.getPointerField(1 * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::riaps::distrcoord::RequestForVoteReq::Pipeline LeaderElection::Pipeline::getRequestForVoteReq() {
  return  ::riaps::distrcoord::RequestForVoteReq::Pipeline(_typeless.getPointerField(1));
}
#endif  // !CAPNP_LITE
inline void LeaderElection::Builder::setRequestForVoteReq( ::riaps::distrcoord::RequestForVoteReq::Reader value) {
  ::capnp::_::PointerHelpers< ::riaps::distrcoord::RequestForVoteReq>::set(
      _builder.getPointerField(1 * ::capnp::POINTERS), value);
}
inline  ::riaps::distrcoord::RequestForVoteReq::Builder LeaderElection::Builder::initRequestForVoteReq() {
  return ::capnp::_::PointerHelpers< ::riaps::distrcoord::RequestForVoteReq>::init(
      _builder.getPointerField(1 * ::capnp::POINTERS));
}
inline void LeaderElection::Builder::adoptRequestForVoteReq(
    ::capnp::Orphan< ::riaps::distrcoord::RequestForVoteReq>&& value) {
  ::capnp::_::PointerHelpers< ::riaps::distrcoord::RequestForVoteReq>::adopt(
      _builder.getPointerField(1 * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::riaps::distrcoord::RequestForVoteReq> LeaderElection::Builder::disownRequestForVoteReq() {
  return ::capnp::_::PointerHelpers< ::riaps::distrcoord::RequestForVoteReq>::disown(
      _builder.getPointerField(1 * ::capnp::POINTERS));
}

inline bool LeaderElection::Reader::hasRequestForVoteRep() const {
  return !_reader.getPointerField(2 * ::capnp::POINTERS).isNull();
}
inline bool LeaderElection::Builder::hasRequestForVoteRep() {
  return !_builder.getPointerField(2 * ::capnp::POINTERS).isNull();
}
inline  ::riaps::distrcoord::RequestForVoteRep::Reader LeaderElection::Reader::getRequestForVoteRep() const {
  return ::capnp::_::PointerHelpers< ::riaps::distrcoord::RequestForVoteRep>::get(
      _reader.getPointerField(2 * ::capnp::POINTERS));
}
inline  ::riaps::distrcoord::RequestForVoteRep::Builder LeaderElection::Builder::getRequestForVoteRep() {
  return ::capnp::_::PointerHelpers< ::riaps::distrcoord::RequestForVoteRep>::get(
      _builder.getPointerField(2 * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::riaps::distrcoord::RequestForVoteRep::Pipeline LeaderElection::Pipeline::getRequestForVoteRep() {
  return  ::riaps::distrcoord::RequestForVoteRep::Pipeline(_typeless.getPointerField(2));
}
#endif  // !CAPNP_LITE
inline void LeaderElection::Builder::setRequestForVoteRep( ::riaps::distrcoord::RequestForVoteRep::Reader value) {
  ::capnp::_::PointerHelpers< ::riaps::distrcoord::RequestForVoteRep>::set(
      _builder.getPointerField(2 * ::capnp::POINTERS), value);
}
inline  ::riaps::distrcoord::RequestForVoteRep::Builder LeaderElection::Builder::initRequestForVoteRep() {
  return ::capnp::_::PointerHelpers< ::riaps::distrcoord::RequestForVoteRep>::init(
      _builder.getPointerField(2 * ::capnp::POINTERS));
}
inline void LeaderElection::Builder::adoptRequestForVoteRep(
    ::capnp::Orphan< ::riaps::distrcoord::RequestForVoteRep>&& value) {
  ::capnp::_::PointerHelpers< ::riaps::distrcoord::RequestForVoteRep>::adopt(
      _builder.getPointerField(2 * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::riaps::distrcoord::RequestForVoteRep> LeaderElection::Builder::disownRequestForVoteRep() {
  return ::capnp::_::PointerHelpers< ::riaps::distrcoord::RequestForVoteRep>::disown(
      _builder.getPointerField(2 * ::capnp::POINTERS));
}

inline  ::riaps::distrcoord::GroupInternals::Which GroupInternals::Reader::which() const {
  return _reader.getDataField<Which>(0 * ::capnp::ELEMENTS);
}
inline  ::riaps::distrcoord::GroupInternals::Which GroupInternals::Builder::which() {
  return _builder.getDataField<Which>(0 * ::capnp::ELEMENTS);
}

inline bool GroupInternals::Reader::isGroupHeartBeat() const {
  return which() == GroupInternals::GROUP_HEART_BEAT;
}
inline bool GroupInternals::Builder::isGroupHeartBeat() {
  return which() == GroupInternals::GROUP_HEART_BEAT;
}
inline bool GroupInternals::Reader::hasGroupHeartBeat() const {
  if (which() != GroupInternals::GROUP_HEART_BEAT) return false;
  return !_reader.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline bool GroupInternals::Builder::hasGroupHeartBeat() {
  if (which() != GroupInternals::GROUP_HEART_BEAT) return false;
  return !_builder.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline  ::riaps::distrcoord::GroupHeartBeat::Reader GroupInternals::Reader::getGroupHeartBeat() const {
  KJ_IREQUIRE(which() == GroupInternals::GROUP_HEART_BEAT,
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::riaps::distrcoord::GroupHeartBeat>::get(
      _reader.getPointerField(0 * ::capnp::POINTERS));
}
inline  ::riaps::distrcoord::GroupHeartBeat::Builder GroupInternals::Builder::getGroupHeartBeat() {
  KJ_IREQUIRE(which() == GroupInternals::GROUP_HEART_BEAT,
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::riaps::distrcoord::GroupHeartBeat>::get(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}
inline void GroupInternals::Builder::setGroupHeartBeat( ::riaps::distrcoord::GroupHeartBeat::Reader value) {
  _builder.setDataField<GroupInternals::Which>(
      0 * ::capnp::ELEMENTS, GroupInternals::GROUP_HEART_BEAT);
  ::capnp::_::PointerHelpers< ::riaps::distrcoord::GroupHeartBeat>::set(
      _builder.getPointerField(0 * ::capnp::POINTERS), value);
}
inline  ::riaps::distrcoord::GroupHeartBeat::Builder GroupInternals::Builder::initGroupHeartBeat() {
  _builder.setDataField<GroupInternals::Which>(
      0 * ::capnp::ELEMENTS, GroupInternals::GROUP_HEART_BEAT);
  return ::capnp::_::PointerHelpers< ::riaps::distrcoord::GroupHeartBeat>::init(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}
inline void GroupInternals::Builder::adoptGroupHeartBeat(
    ::capnp::Orphan< ::riaps::distrcoord::GroupHeartBeat>&& value) {
  _builder.setDataField<GroupInternals::Which>(
      0 * ::capnp::ELEMENTS, GroupInternals::GROUP_HEART_BEAT);
  ::capnp::_::PointerHelpers< ::riaps::distrcoord::GroupHeartBeat>::adopt(
      _builder.getPointerField(0 * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::riaps::distrcoord::GroupHeartBeat> GroupInternals::Builder::disownGroupHeartBeat() {
  KJ_IREQUIRE(which() == GroupInternals::GROUP_HEART_BEAT,
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::riaps::distrcoord::GroupHeartBeat>::disown(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}

inline bool GroupInternals::Reader::isLeaderElection() const {
  return which() == GroupInternals::LEADER_ELECTION;
}
inline bool GroupInternals::Builder::isLeaderElection() {
  return which() == GroupInternals::LEADER_ELECTION;
}
inline bool GroupInternals::Reader::hasLeaderElection() const {
  if (which() != GroupInternals::LEADER_ELECTION) return false;
  return !_reader.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline bool GroupInternals::Builder::hasLeaderElection() {
  if (which() != GroupInternals::LEADER_ELECTION) return false;
  return !_builder.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline  ::riaps::distrcoord::LeaderElection::Reader GroupInternals::Reader::getLeaderElection() const {
  KJ_IREQUIRE(which() == GroupInternals::LEADER_ELECTION,
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::riaps::distrcoord::LeaderElection>::get(
      _reader.getPointerField(0 * ::capnp::POINTERS));
}
inline  ::riaps::distrcoord::LeaderElection::Builder GroupInternals::Builder::getLeaderElection() {
  KJ_IREQUIRE(which() == GroupInternals::LEADER_ELECTION,
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::riaps::distrcoord::LeaderElection>::get(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}
inline void GroupInternals::Builder::setLeaderElection( ::riaps::distrcoord::LeaderElection::Reader value) {
  _builder.setDataField<GroupInternals::Which>(
      0 * ::capnp::ELEMENTS, GroupInternals::LEADER_ELECTION);
  ::capnp::_::PointerHelpers< ::riaps::distrcoord::LeaderElection>::set(
      _builder.getPointerField(0 * ::capnp::POINTERS), value);
}
inline  ::riaps::distrcoord::LeaderElection::Builder GroupInternals::Builder::initLeaderElection() {
  _builder.setDataField<GroupInternals::Which>(
      0 * ::capnp::ELEMENTS, GroupInternals::LEADER_ELECTION);
  return ::capnp::_::PointerHelpers< ::riaps::distrcoord::LeaderElection>::init(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}
inline void GroupInternals::Builder::adoptLeaderElection(
    ::capnp::Orphan< ::riaps::distrcoord::LeaderElection>&& value) {
  _builder.setDataField<GroupInternals::Which>(
      0 * ::capnp::ELEMENTS, GroupInternals::LEADER_ELECTION);
  ::capnp::_::PointerHelpers< ::riaps::distrcoord::LeaderElection>::adopt(
      _builder.getPointerField(0 * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::riaps::distrcoord::LeaderElection> GroupInternals::Builder::disownLeaderElection() {
  KJ_IREQUIRE(which() == GroupInternals::LEADER_ELECTION,
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::riaps::distrcoord::LeaderElection>::disown(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}

}  // namespace
}  // namespace

#endif  // CAPNP_INCLUDED_a5b4ccd232a91945_
