//
// Auto-generated by edu.vanderbilt.riaps.generator.ComponenetGenerator.xtend
//

#ifndef RIAPS_CORE_STIMER_H
#define RIAPS_CORE_STIMER_H

#include "componentmodel/r_componentbase.h"
#include "../../messages-gen/Msg.capnp.h"

// Name of the ports from the model file
#define PORT_TIMER_CLOCK "clock"
#define PORT_SUB_PING "ping"

namespace statictimer {
    namespace components {

        class STimerBase : public riaps::ComponentBase {

        public:
            STimerBase(_component_conf &config, riaps::Actor &actor);

            virtual void OnClock(riaps::ports::PortBase *port)=0;

            virtual void OnPing (const Msg::Reader &message,
                                 riaps::ports::PortBase *port)=0;

            virtual ~STimerBase();
        protected:
            virtual void DispatchMessage(capnp::FlatArrayMessageReader* capnpreader, riaps::ports::PortBase *port,std::shared_ptr<riaps::MessageParams> params=nullptr );
            virtual void DispatchInsideMessage(zmsg_t* zmsg, riaps::ports::PortBase* port);
        };
    }
}
#endif //RIAPS_CORE_STIMER_H
