// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: timersync.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#if CAPNP_VERSION != 8000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


namespace capnp {
namespace schemas {


}  // namespace schemas
}  // namespace capnp

namespace timersync {
namespace messages {

// =======================================================================================

// =======================================================================================

}  // namespace
}  // namespace

