//
// Auto-generated by edu.vanderbilt.riaps.generator.ComponenetGenerator.xtend
//
#ifndef RIAPS_FW_TEMPMONITOR_H
#define RIAPS_FW_TEMPMONITOR_H

#include "base/TempMonitorBase.h"

namespace weathermonitor {
    namespace components {

        class TempMonitor : public TempMonitorBase {

        public:

            TempMonitor(_component_conf_j &config, riaps::Actor &actor);		

            virtual void OnTempupdate(const messages::TempData::Reader &message, riaps::ports::PortBase *port);
            
			virtual void OnOneShotTimer(const std::string& timerid);
			
            virtual ~TempMonitor();


        private:
            std::unique_ptr<std::uniform_real_distribution<double>> unif;
            std::default_random_engine re;
        };
    }
}

extern "C" riaps::ComponentBase* create_component(_component_conf_j&, riaps::Actor& actor);
extern "C" void destroy_component(riaps::ComponentBase*);


#endif //RIAPS_FW_TEMPMONITOR_H		
